// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_providers.sql

package db

import (
	"context"
)

const getModelInformationByNameAndEffort = `-- name: GetModelInformationByNameAndEffort :one
SELECT
    name,
    model,
    effort_level,
    base_url
FROM ai_providers
WHERE name = $1 AND model = $2 AND effort_level = $3
`

type GetModelInformationByNameAndEffortParams struct {
	Name        string
	Model       string
	EffortLevel string
}

type GetModelInformationByNameAndEffortRow struct {
	Name        string
	Model       string
	EffortLevel string
	BaseUrl     string
}

func (q *Queries) GetModelInformationByNameAndEffort(ctx context.Context, arg GetModelInformationByNameAndEffortParams) (GetModelInformationByNameAndEffortRow, error) {
	row := q.db.QueryRow(ctx, getModelInformationByNameAndEffort, arg.Name, arg.Model, arg.EffortLevel)
	var i GetModelInformationByNameAndEffortRow
	err := row.Scan(
		&i.Name,
		&i.Model,
		&i.EffortLevel,
		&i.BaseUrl,
	)
	return i, err
}

const listEffortsByProviderAndModel = `-- name: ListEffortsByProviderAndModel :many
SELECT DISTINCT effort_level
FROM ai_providers
WHERE enabled = true AND name = $1 AND model = $2
ORDER BY effort_level
`

type ListEffortsByProviderAndModelParams struct {
	Name  string
	Model string
}

func (q *Queries) ListEffortsByProviderAndModel(ctx context.Context, arg ListEffortsByProviderAndModelParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listEffortsByProviderAndModel, arg.Name, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var effort_level string
		if err := rows.Scan(&effort_level); err != nil {
			return nil, err
		}
		items = append(items, effort_level)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledProviders = `-- name: ListEnabledProviders :many
SELECT
    name,
    model,
    effort_level,
    description,
    base_url,
    enabled
FROM ai_providers
WHERE enabled = true
ORDER BY name, model, effort_level
`

type ListEnabledProvidersRow struct {
	Name        string
	Model       string
	EffortLevel string
	Description string
	BaseUrl     string
	Enabled     bool
}

func (q *Queries) ListEnabledProviders(ctx context.Context) ([]ListEnabledProvidersRow, error) {
	rows, err := q.db.Query(ctx, listEnabledProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnabledProvidersRow
	for rows.Next() {
		var i ListEnabledProvidersRow
		if err := rows.Scan(
			&i.Name,
			&i.Model,
			&i.EffortLevel,
			&i.Description,
			&i.BaseUrl,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsByProviderName = `-- name: ListModelsByProviderName :many
SELECT DISTINCT model
FROM ai_providers
WHERE enabled = true AND name = $1
ORDER BY model
`

func (q *Queries) ListModelsByProviderName(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, listModelsByProviderName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var model string
		if err := rows.Scan(&model); err != nil {
			return nil, err
		}
		items = append(items, model)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
