// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNumberApplications = `-- name: CountNumberApplications :one
SELECT COUNT(*) FROM applications WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountNumberApplications(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countNumberApplications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNumberInterviews = `-- name: CountNumberInterviews :one
SELECT COUNT(*) FROM applications WHERE user_id = $1 AND status = 'Interview' AND deleted_at IS NULL
`

func (q *Queries) CountNumberInterviews(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countNumberInterviews, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNumberPending = `-- name: CountNumberPending :one
SELECT COUNT(*) FROM applications WHERE user_id = $1 AND status = 'Applied' AND deleted_at IS NULL
`

func (q *Queries) CountNumberPending(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countNumberPending, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    user_id, company_name, company_website, role, work_model, sector, location, salary, date, link, contact_linkedin_profile, status, interview_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id
`

type CreateApplicationParams struct {
	UserID                 int32
	CompanyName            string
	CompanyWebsite         pgtype.Text
	Role                   string
	WorkModel              string
	Sector                 pgtype.Text
	Location               pgtype.Text
	Salary                 pgtype.Text
	Date                   pgtype.Date
	Link                   pgtype.Text
	ContactLinkedinProfile pgtype.Text
	Status                 TypApplicationStatus
	InterviewDate          pgtype.Date
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (int32, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.UserID,
		arg.CompanyName,
		arg.CompanyWebsite,
		arg.Role,
		arg.WorkModel,
		arg.Sector,
		arg.Location,
		arg.Salary,
		arg.Date,
		arg.Link,
		arg.ContactLinkedinProfile,
		arg.Status,
		arg.InterviewDate,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteApplication = `-- name: DeleteApplication :exec
UPDATE applications SET deleted_at = NOW() WHERE id = $1 AND user_id = $2
`

type DeleteApplicationParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteApplication(ctx context.Context, arg DeleteApplicationParams) error {
	_, err := q.db.Exec(ctx, deleteApplication, arg.ID, arg.UserID)
	return err
}

const getAllUserApplications = `-- name: GetAllUserApplications :many
SELECT
    id,
    user_id,
    company_name,
    company_website,
    role,
    work_model,
    sector,
    location,
    salary,
    date,
    link,
    contact_linkedin_profile,
    status,
    last_follow_up_contact_at,
    interview_date
FROM applications
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetAllUserApplicationsRow struct {
	ID                     int32
	UserID                 int32
	CompanyName            string
	CompanyWebsite         pgtype.Text
	Role                   string
	WorkModel              string
	Sector                 pgtype.Text
	Location               pgtype.Text
	Salary                 pgtype.Text
	Date                   pgtype.Date
	Link                   pgtype.Text
	ContactLinkedinProfile pgtype.Text
	Status                 TypApplicationStatus
	LastFollowUpContactAt  pgtype.Date
	InterviewDate          pgtype.Date
}

func (q *Queries) GetAllUserApplications(ctx context.Context, userID int32) ([]GetAllUserApplicationsRow, error) {
	rows, err := q.db.Query(ctx, getAllUserApplications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserApplicationsRow
	for rows.Next() {
		var i GetAllUserApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyName,
			&i.CompanyWebsite,
			&i.Role,
			&i.WorkModel,
			&i.Sector,
			&i.Location,
			&i.Salary,
			&i.Date,
			&i.Link,
			&i.ContactLinkedinProfile,
			&i.Status,
			&i.LastFollowUpContactAt,
			&i.InterviewDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserApplicationsByAllFilters = `-- name: GetAllUserApplicationsByAllFilters :many
SELECT
    id,
    user_id,
    company_name,
    company_website,
    role,
    work_model,
    sector,
    location,
    salary,
    date,
    link,
    contact_linkedin_profile,
    status,
    last_follow_up_contact_at,
    interview_date
FROM applications
WHERE user_id = $1
AND status = $2
AND (LOWER(company_name) LIKE '%' || $3 || '%' OR role LIKE '%' || $3 || '%')
AND deleted_at IS NULL
`

type GetAllUserApplicationsByAllFiltersParams struct {
	UserID  int32
	Status  TypApplicationStatus
	Column3 pgtype.Text
}

type GetAllUserApplicationsByAllFiltersRow struct {
	ID                     int32
	UserID                 int32
	CompanyName            string
	CompanyWebsite         pgtype.Text
	Role                   string
	WorkModel              string
	Sector                 pgtype.Text
	Location               pgtype.Text
	Salary                 pgtype.Text
	Date                   pgtype.Date
	Link                   pgtype.Text
	ContactLinkedinProfile pgtype.Text
	Status                 TypApplicationStatus
	LastFollowUpContactAt  pgtype.Date
	InterviewDate          pgtype.Date
}

func (q *Queries) GetAllUserApplicationsByAllFilters(ctx context.Context, arg GetAllUserApplicationsByAllFiltersParams) ([]GetAllUserApplicationsByAllFiltersRow, error) {
	rows, err := q.db.Query(ctx, getAllUserApplicationsByAllFilters, arg.UserID, arg.Status, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserApplicationsByAllFiltersRow
	for rows.Next() {
		var i GetAllUserApplicationsByAllFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyName,
			&i.CompanyWebsite,
			&i.Role,
			&i.WorkModel,
			&i.Sector,
			&i.Location,
			&i.Salary,
			&i.Date,
			&i.Link,
			&i.ContactLinkedinProfile,
			&i.Status,
			&i.LastFollowUpContactAt,
			&i.InterviewDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserApplicationsByNameOrCompany = `-- name: GetAllUserApplicationsByNameOrCompany :many
SELECT
    id,
    user_id,
    company_name,
    company_website,
    role,
    work_model,
    sector,
    location,
    salary,
    date,
    link,
    contact_linkedin_profile,
    status,
    last_follow_up_contact_at,
    interview_date
FROM applications
WHERE user_id = $1
AND (LOWER(company_name) LIKE '%' || $2 || '%' OR role LIKE '%' || $2 || '%')
AND deleted_at IS NULL
`

type GetAllUserApplicationsByNameOrCompanyParams struct {
	UserID  int32
	Column2 pgtype.Text
}

type GetAllUserApplicationsByNameOrCompanyRow struct {
	ID                     int32
	UserID                 int32
	CompanyName            string
	CompanyWebsite         pgtype.Text
	Role                   string
	WorkModel              string
	Sector                 pgtype.Text
	Location               pgtype.Text
	Salary                 pgtype.Text
	Date                   pgtype.Date
	Link                   pgtype.Text
	ContactLinkedinProfile pgtype.Text
	Status                 TypApplicationStatus
	LastFollowUpContactAt  pgtype.Date
	InterviewDate          pgtype.Date
}

func (q *Queries) GetAllUserApplicationsByNameOrCompany(ctx context.Context, arg GetAllUserApplicationsByNameOrCompanyParams) ([]GetAllUserApplicationsByNameOrCompanyRow, error) {
	rows, err := q.db.Query(ctx, getAllUserApplicationsByNameOrCompany, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserApplicationsByNameOrCompanyRow
	for rows.Next() {
		var i GetAllUserApplicationsByNameOrCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyName,
			&i.CompanyWebsite,
			&i.Role,
			&i.WorkModel,
			&i.Sector,
			&i.Location,
			&i.Salary,
			&i.Date,
			&i.Link,
			&i.ContactLinkedinProfile,
			&i.Status,
			&i.LastFollowUpContactAt,
			&i.InterviewDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserApplicationsByStatus = `-- name: GetAllUserApplicationsByStatus :many
SELECT
    id,
    user_id,
    company_name,
    company_website,
    role,
    work_model,
    sector,
    location,
    salary,
    date,
    link,
    contact_linkedin_profile,
    status,
    last_follow_up_contact_at,
    interview_date
FROM applications
WHERE user_id = $1
AND status = $2
AND deleted_at IS NULL
`

type GetAllUserApplicationsByStatusParams struct {
	UserID int32
	Status TypApplicationStatus
}

type GetAllUserApplicationsByStatusRow struct {
	ID                     int32
	UserID                 int32
	CompanyName            string
	CompanyWebsite         pgtype.Text
	Role                   string
	WorkModel              string
	Sector                 pgtype.Text
	Location               pgtype.Text
	Salary                 pgtype.Text
	Date                   pgtype.Date
	Link                   pgtype.Text
	ContactLinkedinProfile pgtype.Text
	Status                 TypApplicationStatus
	LastFollowUpContactAt  pgtype.Date
	InterviewDate          pgtype.Date
}

func (q *Queries) GetAllUserApplicationsByStatus(ctx context.Context, arg GetAllUserApplicationsByStatusParams) ([]GetAllUserApplicationsByStatusRow, error) {
	rows, err := q.db.Query(ctx, getAllUserApplicationsByStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserApplicationsByStatusRow
	for rows.Next() {
		var i GetAllUserApplicationsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyName,
			&i.CompanyWebsite,
			&i.Role,
			&i.WorkModel,
			&i.Sector,
			&i.Location,
			&i.Salary,
			&i.Date,
			&i.Link,
			&i.ContactLinkedinProfile,
			&i.Status,
			&i.LastFollowUpContactAt,
			&i.InterviewDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT
    id,
    user_id,
    company_name,
    company_website,
    role,
    work_model,
    sector,
    location,
    salary,
    date,
    link,
    contact_linkedin_profile,
    status,
    last_follow_up_contact_at,
    interview_date
FROM applications
WHERE id = $1 AND deleted_at IS NULL
`

type GetApplicationByIDRow struct {
	ID                     int32
	UserID                 int32
	CompanyName            string
	CompanyWebsite         pgtype.Text
	Role                   string
	WorkModel              string
	Sector                 pgtype.Text
	Location               pgtype.Text
	Salary                 pgtype.Text
	Date                   pgtype.Date
	Link                   pgtype.Text
	ContactLinkedinProfile pgtype.Text
	Status                 TypApplicationStatus
	LastFollowUpContactAt  pgtype.Date
	InterviewDate          pgtype.Date
}

func (q *Queries) GetApplicationByID(ctx context.Context, id int32) (GetApplicationByIDRow, error) {
	row := q.db.QueryRow(ctx, getApplicationByID, id)
	var i GetApplicationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.CompanyWebsite,
		&i.Role,
		&i.WorkModel,
		&i.Sector,
		&i.Location,
		&i.Salary,
		&i.Date,
		&i.Link,
		&i.ContactLinkedinProfile,
		&i.Status,
		&i.LastFollowUpContactAt,
		&i.InterviewDate,
	)
	return i, err
}

const isOwner = `-- name: IsOwner :one
SELECT EXISTS(SELECT 1 FROM applications WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL)
`

type IsOwnerParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) IsOwner(ctx context.Context, arg IsOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOwner, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE applications SET
    company_name = $2,
    company_website = $3,
    role = $4,
    work_model = $5,
    sector = $6,
    location = $7,
    salary = $8,
    date = $9,
    link = $10,
    contact_linkedin_profile = $11,
    status = $12,
    last_follow_up_contact_at = $13,
    interview_date = $14
WHERE id = $1 AND user_id = $15
`

type UpdateApplicationParams struct {
	ID                     int32
	CompanyName            string
	CompanyWebsite         pgtype.Text
	Role                   string
	WorkModel              string
	Sector                 pgtype.Text
	Location               pgtype.Text
	Salary                 pgtype.Text
	Date                   pgtype.Date
	Link                   pgtype.Text
	ContactLinkedinProfile pgtype.Text
	Status                 TypApplicationStatus
	LastFollowUpContactAt  pgtype.Date
	InterviewDate          pgtype.Date
	UserID                 int32
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.Exec(ctx, updateApplication,
		arg.ID,
		arg.CompanyName,
		arg.CompanyWebsite,
		arg.Role,
		arg.WorkModel,
		arg.Sector,
		arg.Location,
		arg.Salary,
		arg.Date,
		arg.Link,
		arg.ContactLinkedinProfile,
		arg.Status,
		arg.LastFollowUpContactAt,
		arg.InterviewDate,
		arg.UserID,
	)
	return err
}

const updateFollowUpDate = `-- name: UpdateFollowUpDate :exec
UPDATE applications SET last_follow_up_contact_at = $2 WHERE id = $1 AND user_id = $3
`

type UpdateFollowUpDateParams struct {
	ID                    int32
	LastFollowUpContactAt pgtype.Date
	UserID                int32
}

func (q *Queries) UpdateFollowUpDate(ctx context.Context, arg UpdateFollowUpDateParams) error {
	_, err := q.db.Exec(ctx, updateFollowUpDate, arg.ID, arg.LastFollowUpContactAt, arg.UserID)
	return err
}
