// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cvs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCV = `-- name: CreateCV :one
INSERT INTO cvs (
    user_id,
    title,
    summary,
    profile,
    experiences,
    education,
    certifications,
    academic_contributions,
    skills
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id
`

type CreateCVParams struct {
	UserID                int32
	Title                 string
	Summary               pgtype.Text
	Profile               json.RawMessage
	Experiences           json.RawMessage
	Education             pgtype.Text
	Certifications        pgtype.Text
	AcademicContributions pgtype.Text
	Skills                pgtype.Text
}

func (q *Queries) CreateCV(ctx context.Context, arg CreateCVParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCV,
		arg.UserID,
		arg.Title,
		arg.Summary,
		arg.Profile,
		arg.Experiences,
		arg.Education,
		arg.Certifications,
		arg.AcademicContributions,
		arg.Skills,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteCV = `-- name: DeleteCV :exec
UPDATE cvs SET
    deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type DeleteCVParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteCV(ctx context.Context, arg DeleteCVParams) error {
	_, err := q.db.Exec(ctx, deleteCV, arg.ID, arg.UserID)
	return err
}

const getAllUserCVs = `-- name: GetAllUserCVs :many
SELECT
    id,
    user_id,
    title,
    summary,
    profile,
    experiences,
    education,
    certifications,
    academic_contributions,
    skills,
    created_at,
    updated_at
FROM cvs
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type GetAllUserCVsRow struct {
	ID                    int32
	UserID                int32
	Title                 string
	Summary               pgtype.Text
	Profile               json.RawMessage
	Experiences           json.RawMessage
	Education             pgtype.Text
	Certifications        pgtype.Text
	AcademicContributions pgtype.Text
	Skills                pgtype.Text
	CreatedAt             pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
}

func (q *Queries) GetAllUserCVs(ctx context.Context, userID int32) ([]GetAllUserCVsRow, error) {
	rows, err := q.db.Query(ctx, getAllUserCVs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserCVsRow
	for rows.Next() {
		var i GetAllUserCVsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Summary,
			&i.Profile,
			&i.Experiences,
			&i.Education,
			&i.Certifications,
			&i.AcademicContributions,
			&i.Skills,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCVByID = `-- name: GetCVByID :one
SELECT
    id,
    user_id,
    title,
    summary,   
    profile,
    experiences,
    education,
    certifications,
    academic_contributions,
    skills,
    created_at,
    updated_at
FROM cvs
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetCVByIDParams struct {
	ID     int32
	UserID int32
}

type GetCVByIDRow struct {
	ID                    int32
	UserID                int32
	Title                 string
	Summary               pgtype.Text
	Profile               json.RawMessage
	Experiences           json.RawMessage
	Education             pgtype.Text
	Certifications        pgtype.Text
	AcademicContributions pgtype.Text
	Skills                pgtype.Text
	CreatedAt             pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
}

func (q *Queries) GetCVByID(ctx context.Context, arg GetCVByIDParams) (GetCVByIDRow, error) {
	row := q.db.QueryRow(ctx, getCVByID, arg.ID, arg.UserID)
	var i GetCVByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Summary,
		&i.Profile,
		&i.Experiences,
		&i.Education,
		&i.Certifications,
		&i.AcademicContributions,
		&i.Skills,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isCVOwner = `-- name: IsCVOwner :one
SELECT EXISTS(
    SELECT 1 FROM cvs
    WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
)
`

type IsCVOwnerParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) IsCVOwner(ctx context.Context, arg IsCVOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCVOwner, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateCV = `-- name: UpdateCV :exec
UPDATE cvs SET
    title = $2,
    summary = $3,
    profile = $4,
    experiences = $5,
    education = $6,
    certifications = $7,
    academic_contributions = $8,
    skills = $9,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $10 AND deleted_at IS NULL
`

type UpdateCVParams struct {
	ID                    int32
	Title                 string
	Summary               pgtype.Text
	Profile               json.RawMessage
	Experiences           json.RawMessage
	Education             pgtype.Text
	Certifications        pgtype.Text
	AcademicContributions pgtype.Text
	Skills                pgtype.Text
	UserID                int32
}

func (q *Queries) UpdateCV(ctx context.Context, arg UpdateCVParams) error {
	_, err := q.db.Exec(ctx, updateCV,
		arg.ID,
		arg.Title,
		arg.Summary,
		arg.Profile,
		arg.Experiences,
		arg.Education,
		arg.Certifications,
		arg.AcademicContributions,
		arg.Skills,
		arg.UserID,
	)
	return err
}
