// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TypApplicationStatus string

const (
	TypApplicationStatusApplied    TypApplicationStatus = "Applied"
	TypApplicationStatusNotApplied TypApplicationStatus = "Not Applied"
	TypApplicationStatusProcessing TypApplicationStatus = "Processing"
	TypApplicationStatusInterview  TypApplicationStatus = "Interview"
	TypApplicationStatusOffer      TypApplicationStatus = "Offer"
	TypApplicationStatusRejected   TypApplicationStatus = "Rejected"
)

func (e *TypApplicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypApplicationStatus(s)
	case string:
		*e = TypApplicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TypApplicationStatus: %T", src)
	}
	return nil
}

type NullTypApplicationStatus struct {
	TypApplicationStatus TypApplicationStatus
	Valid                bool // Valid is true if TypApplicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypApplicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TypApplicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypApplicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypApplicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypApplicationStatus), nil
}

type TypWorkModel string

const (
	TypWorkModelRemote       TypWorkModel = "Remote"
	TypWorkModelHybrid       TypWorkModel = "Hybrid"
	TypWorkModelOnsite       TypWorkModel = "Onsite"
	TypWorkModelNotSpecified TypWorkModel = "Not Specified"
)

func (e *TypWorkModel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TypWorkModel(s)
	case string:
		*e = TypWorkModel(s)
	default:
		return fmt.Errorf("unsupported scan type for TypWorkModel: %T", src)
	}
	return nil
}

type NullTypWorkModel struct {
	TypWorkModel TypWorkModel
	Valid        bool // Valid is true if TypWorkModel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTypWorkModel) Scan(value interface{}) error {
	if value == nil {
		ns.TypWorkModel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TypWorkModel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTypWorkModel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TypWorkModel), nil
}

type AiProvider struct {
	ID          int32
	Name        string
	Model       string
	EffortLevel string
	Description string
	BaseUrl     string
	Enabled     bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type Application struct {
	ID                     int32
	UserID                 int32
	CompanyName            string
	CompanyWebsite         pgtype.Text
	Role                   string
	WorkModel              string
	Sector                 pgtype.Text
	Location               pgtype.Text
	Salary                 pgtype.Text
	Date                   pgtype.Date
	Link                   pgtype.Text
	ContactLinkedinProfile pgtype.Text
	Status                 TypApplicationStatus
	LastFollowUpContactAt  pgtype.Date
	InterviewDate          pgtype.Date
	JobDescription         pgtype.Text
	ChosenCvID             pgtype.Int4
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
	DeletedAt              pgtype.Timestamp
}

type Cv struct {
	ID                    int32
	UserID                int32
	Title                 string
	Summary               pgtype.Text
	Profile               json.RawMessage
	Experiences           json.RawMessage
	Education             pgtype.Text
	Certifications        pgtype.Text
	AcademicContributions pgtype.Text
	Skills                pgtype.Text
	CreatedAt             pgtype.Timestamp
	UpdatedAt             pgtype.Timestamp
	DeletedAt             pgtype.Timestamp
}

type Note struct {
	ID         int32
	UserID     int32
	NoteHeader string
	NoteText   pgtype.Text
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type Session struct {
	ID           string
	UserID       int32
	IpAddress    string
	UserAgent    string
	CreatedAt    pgtype.Timestamp
	LastActivity pgtype.Timestamp
	ExpiresAt    pgtype.Timestamp
}

type User struct {
	ID        int32
	Email     string
	Username  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type UserAiSetting struct {
	UserID       int32
	ProviderName string
	ModelName    string
	EffortLevel  string
	Key          pgtype.Text
	Enabled      bool
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
