// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, note_header, note_text)
VALUES ($1, $2, $3)
RETURNING id, user_id, note_header, note_text, created_at, updated_at, deleted_at
`

type CreateNoteParams struct {
	UserID     int32
	NoteHeader string
	NoteText   pgtype.Text
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.UserID, arg.NoteHeader, arg.NoteText)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteHeader,
		&i.NoteText,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
UPDATE notes
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type DeleteNoteParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.UserID)
	return err
}

const getAllUserNotes = `-- name: GetAllUserNotes :many
SELECT id, user_id, note_header, note_text, created_at, updated_at, deleted_at FROM notes
WHERE user_id = $1
AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllUserNotes(ctx context.Context, userID int32) ([]Note, error) {
	rows, err := q.db.Query(ctx, getAllUserNotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NoteHeader,
			&i.NoteText,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, user_id, note_header, note_text, created_at, updated_at, deleted_at FROM notes
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetNoteByIDParams struct {
	ID     int32
	UserID int32
}

func (q *Queries) GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByID, arg.ID, arg.UserID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NoteHeader,
		&i.NoteText,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :exec
UPDATE notes
SET note_header = $2,
    note_text = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $4
`

type UpdateNoteParams struct {
	ID         int32
	NoteHeader string
	NoteText   pgtype.Text
	UserID     int32
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) error {
	_, err := q.db.Exec(ctx, updateNote,
		arg.ID,
		arg.NoteHeader,
		arg.NoteText,
		arg.UserID,
	)
	return err
}
