// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :execresult
INSERT INTO sessions (id, user_id, ip_address, user_agent, created_at, last_activity, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSessionParams struct {
	ID           string
	UserID       int32
	IpAddress    string
	UserAgent    string
	CreatedAt    pgtype.Timestamp
	LastActivity pgtype.Timestamp
	ExpiresAt    pgtype.Timestamp
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.IpAddress,
		arg.UserAgent,
		arg.CreatedAt,
		arg.LastActivity,
		arg.ExpiresAt,
	)
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, ip_address, user_agent, created_at, last_activity, expires_at FROM sessions WHERE id = $1 AND expires_at > NOW()
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastActivity,
		&i.ExpiresAt,
	)
	return i, err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions SET last_activity = $1, expires_at = $2 WHERE id = $3
`

type UpdateSessionActivityParams struct {
	LastActivity pgtype.Timestamp
	ExpiresAt    pgtype.Timestamp
	ID           string
}

func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error {
	_, err := q.db.Exec(ctx, updateSessionActivity, arg.LastActivity, arg.ExpiresAt, arg.ID)
	return err
}
