// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_ai_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserAISettings = `-- name: GetUserAISettings :one
SELECT
    user_id,
    provider_name,
    model_name,
    effort_level,
    key,
    enabled,
    created_at,
    updated_at
FROM user_ai_settings
WHERE user_id = $1
`

func (q *Queries) GetUserAISettings(ctx context.Context, userID int32) (UserAiSetting, error) {
	row := q.db.QueryRow(ctx, getUserAISettings, userID)
	var i UserAiSetting
	err := row.Scan(
		&i.UserID,
		&i.ProviderName,
		&i.ModelName,
		&i.EffortLevel,
		&i.Key,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserAISettings = `-- name: UpsertUserAISettings :exec
INSERT INTO user_ai_settings (
    user_id,
    provider_name,
    model_name,
    effort_level,
    key,
    enabled
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id) DO UPDATE SET
    provider_name = EXCLUDED.provider_name,
    model_name = EXCLUDED.model_name,
    effort_level = EXCLUDED.effort_level,
    key = EXCLUDED.key,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertUserAISettingsParams struct {
	UserID       int32
	ProviderName string
	ModelName    string
	EffortLevel  string
	Key          pgtype.Text
	Enabled      bool
}

func (q *Queries) UpsertUserAISettings(ctx context.Context, arg UpsertUserAISettingsParams) error {
	_, err := q.db.Exec(ctx, upsertUserAISettings,
		arg.UserID,
		arg.ProviderName,
		arg.ModelName,
		arg.EffortLevel,
		arg.Key,
		arg.Enabled,
	)
	return err
}
